### ISSUE TITLE
Exemple non conforme

### ISSUE THREAD

**Issue by johanricher** [etalab/schema-irve#10]
Dans la dernière version du schéma IRVE, le format date a évolué (séparateur `-` plutôt que `/`) mais l'exemple donné n'a pas été mis à jour :
```
            "name": "date_maj",
            "description": "Date de mise à jour des données",
            "example": "2018/08/08, 2015/12/30",
            "type": "date",
            "format": "%Y-%m-%d",
            "constraints": {
                "required": true
```
https://github.com/etalab/schema-irve/blob/v2.0.0/schema.json#L451

J'en profite pour signaler l'idée que les valeurs exemples soient vérifiées par le validateur, et vous encourage à la soutenir et la discuter : https://github.com/frictionlessdata/specs/issues/740

**Comment by AntoineAugusti** [comment]
@geoffreyaldebert @abulte  Je peux faire une PR et tagguer une 2.0.2 après le merge de #11. Ça vous irait ?

**Comment by geoffreyaldebert** [comment]
Merci @johanricher 
Ok @AntoineAugusti merci pour la proposition, je fais la release de la 2.0.1 puis j'enchainerai avec ta PR.

**Comment by AntoineAugusti** [comment]
@geoffreyaldebert Voici la PR https://github.com/etalab/schema-irve/pull/12
