### ISSUE TITLE
Choisir une stratégie "identifiants des schémas" pour la mise en place du dynamique

### ISSUE THREAD

**Issue by thbar** [etalab/schema-irve#26]
Je crée un ticket spécifique pour qu'on puisse clairement avancer là dessus, en lien avec :

- https://github.com/etalab/schema-irve/pull/21

Actuellement, en [version 2.1.0](https://github.com/etalab/schema-irve/releases/tag/v2.1.0), une ressource data gouv est marquée "ressource statique IRVE" dès lors que son `schema` est égal à `etalab/schema-irve` (car, si j'ai compris, le nom du repository où le schéma est déclaré est lui-même `etalab/schema-irve`).

Toutefois, la consolidation (https://github.com/etalab/notebooks/blob/master/irve-v2/consolidation-irve-v2.ipynb) brasse plus large, et il va falloir revoir cela pour pouvoir faire le tri entre le statique et le dynamique :
- https://www.data.gouv.fr/api/1/datasets/?tag=irve
- https://www.data.gouv.fr/api/1/datasets/?schema=etalab/schema-irve
- https://www.data.gouv.fr/api/1/datasets/?q=recharge+v%C3%A9hicules+%C3%A9lectrique
- https://www.data.gouv.fr/api/1/datasets/?q=irve

Je déduis une première tâche : il va falloir que la consolidation statique n'aille chercher que "par schéma", pour éviter de récupérer des jeux dynamiques au passage.

Ensuite, il faut préparer le merge de https://github.com/etalab/schema-irve/pull/21.

Je me demande si on peut maintenir une rétro-compatibilité de l'identifiant du schéma statique, pour conserver `etalab/schema-irve`. J'ai essayé de maintenir cette rétro-compatibilité ici :
- https://github.com/etalab/schema-irve/pull/21/files#diff-68671d3f892e88cee6ab150df89a38bd0bc6eafd69c404c5807abc261c0efeeaR2

Je déduis une deuxième tâche : confirmer avec @geoffreyaldebert que si on a le name `schema-irve` comme spécifié actuellement dans la PR, l'identifiant de schéma resterait si je comprends `etalab/schema-irve`.

Si c'est le cas, on pourrait aussi nommer le schéma dynamique `schema-irve-dynamique` (à modifier ici https://github.com/etalab/schema-irve/pull/21/files#diff-2621fa081e1f7d1d72b4097e61896f50e0de11f3cab99902b683725f90696e7aR3), ce qui donnerait un nom complet de `etalab/schema-irve-dynamique`.

En résumé, de cette façon:
- le statique resterait désigné par `etalab/schema-irve`
- le dynamique serait désigné par `etalab/schema-irve-dynamique`
- la consolidation statique serait modifiée pour ne cibler que `schema=etalab/schema-irve`, sans risque d'ambiguité
- une consolidation dynamique future, ou une recherche sur `etalab/schema-irve-dynamique`, serait plus simple à mettre en oeuvre.

Point à discuter avant la finalisation donc, poke @geoffreyaldebert !

**Comment by geoffreyaldebert** [comment]
Hello !
Du coup j'ai commenté ta PR actuel. En synthèse, c'est possible mais il faut faire quelques actions : 
- changer le nom du repo `schema-irve`. Par exemple `datapackage-irve` (pour éviter un conflit entre le nom du datapackage et le nom d'un table schema).
- Partir comme tu l'imagines en nommant le schéma statique `schema-irve` dans la propriété `name` du schéma.
- Partir comme tu l'imagines en nommant le schéma dynamique `schema-irve-dynamique` dans la propriété `name` du schéma.

**Comment by fchabouis** [comment]
Après discussion avec @Benoit-MINT et @ChristinaLaumond, nous avons décidé d'avoir l'url existante etalab/schema-irve qui pointe vers le datapackage, puis etalab/schema-irve-statique et etalab/schema-irve-dynamique qui pointent vers les schémas enfants. Donc pas besoin de changer le nom du repo. L'article de loi sera adapté en ce sens, il devait être modifié de toutes les façons pour prendre en compte les données dynamiques.

**Comment by thbar** [comment]
> etalab/schema-irve-statique

@fchabouis est-ce que ça peut être `etalab/schema-irve` à la place ? Pour des questions de rétro-compatibilité ?

**Comment by fchabouis** [comment]
Non, parce que `etalab/schema-irve` va pointer vers le datapackage qui sera à la racine des deux schémas. Donc ça ne va pas completement casser l'url, ça amenera vers la page qui liste les 2 schémas à la place.

**Comment by thbar** [comment]
Nous avons au final procédé au changement, et suivi ce qui est dans le [commentaire de Francis plus haut](https://github.com/etalab/schema-irve/issues/26#issuecomment-1352743140)

> nous avons décidé d'avoir l'url existante etalab/schema-irve qui pointe vers le datapackage, puis etalab/schema-irve-statique et etalab/schema-irve-dynamique qui pointent vers les schémas enfants. Donc pas besoin de changer le nom du repo.

Vérifications effectuées ce jour:
- le repo n'a pas changé de nom
- l'identifiant `etalab/irve-statique` est abandonné (et poke @cyrilmorin j'ai bien vérifié comme toi qu'on n'a plus rien dessus, cf https://www.data.gouv.fr/fr/datasets/?schema=etalab%2Fschema-irve)
- les schémas de références sont https://schema.data.gouv.fr/etalab/schema-irve-statique/ et https://schema.data.gouv.fr/etalab/schema-irve-dynamique/

Reste la question de l'adaptation du texte de loi - je ne sais pas si ça a été fait ou pas, donc j'ai lancé une discussion Mattermost avec @Benoit-MINT, je conserve donc ce ticket ouvert pour le moment.

> L'article de loi sera adapté en ce sens, il devait être modifié de toutes les façons pour prendre en compte les données dynamiques.

**Comment by thbar** [comment]
Merci @geoffreyaldebert @fchabouis sur ces sujets ! 🥳
