### ISSUE TITLE
Questions sur la consolidation des données accessibles sur data.gouv.fr

### ISSUE THREAD

**Issue by garaud** [etalab/schema-irve#3]
Bonjour,

J'ai commencé à jeter un œil au fichier notebook d'agrégation des données. Merci et bravo pour le travail effectué pour récupérer toutes ces données.

* Je souhaite savoir si les données consolidées accessibles via la plate-forme data.gouv  https://www.data.gouv.fr/fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/ sont issues de ce travail ?

* Est-ce que ce fichier consolidé passe la validation du schéma spécifié par le fichier `schema.json` ? Je le fais tourner avec l'outil [goodtables](http://pypi.python.org/pypi/goodtables) et j'ai pas moins de 19,000 erreurs

* Au delà de la validation du schéma stricte, j'ai eu quelques blagues dans les données avec des champs décalés, e.g. l'id du point de charge à la place du nombre de point de charges. Ce dernier étant considéré comme un entier fait logiquement planter mon import dans une base postgres. Est-ce qu'il ne serait pas possible de remonter les potentielles erreurs de validation du schéma aux producteurs de données, ou a minima ne pas les insérer dans le fichier de consolidation ?

Merci et à bientôt,
Damien G.

**Comment by abulte** [comment]
Bonjour,

C'est effectivement https://github.com/etalab/schema-irve/blob/master/aggregration/irve.ipynb qui est utilisé pour la consolidation (je viens de le mettre à jour).

Ce fichier ne passe pas par la validation via le schéma. L'initiative de consolidation est antérieure à celle de validation des données chez nous. C'est effectivement quelque chose à faire 👍, le seul problème étant que ça risque encore de réduire le nombre de bornes disponibles dans le fichier consolidé, vue la qualité des données en entrée...

Un retour aux producteurs sur la qualité de leur donnée est effectivement envisagé. Nous avons les solutions techniques pour le faire (passage du schéma via https://go.validata.fr et envoi d'un commentaire sur data.gouv.fr). Toutefois, la charge de support engendrée par ce genre d'initiatives est conséquente. De plus, il nous manque encore la brique de validation au niveau de la contribution sur data.gouv.fr, ce qui pourrait certainement faciliter et améliorer les choses.

**Comment by garaud** [comment]
Merci beaucoup pour cette réponse. Ça répond à mes questions. Merci :slightly_smiling_face:
