### ISSUE TITLE
A quoi sert la propriété "path" ?

### ISSUE THREAD

**Issue by fchabouis** [etalab/schema-irve#34]
Salut @geoffreyaldebert ,
on se demandait avec @Miryad3108 à quoi servait cette propriété "path". J'ai l'impression qu'elle ne sert peut-être à rien ?
Merci !

https://github.com/etalab/schema-irve/blob/a5a6c59e49d13fd67cf24893d1a4c960c1ab0873/datapackage.json#L9

**Comment by thbar** [comment]
Je retrouve bien `path` dans la spécification ici:
- https://specs.frictionlessdata.io/data-resource/#data-location

Mais l'usage n'est pas encore clair.

Je garde ouvert et on revisitera ça.

**Comment by johanricher** [comment]
Ca sert à indiquer l'URL (path) d'un fichier exemple (ici un exemple valide), de façon similaire au schéma dans sa version antérieure :

https://github.com/etalab/schema-irve/blob/v2.1.0/schema.json#L12

L'utilisation de cette propriété resources->path est décrite dans [ce "pattern"](https://specs.frictionlessdata.io/patterns/#specification-9), qui sert de complément à la spec Table Schema.

Pour le contexte, il faut aussi ne pas oublier que l'utilisation de la spec Data Package pour regrouper plusieurs Table Schema, comme ici, est un hack custom et pas conforme ni à la spec Table Schema ni à la spec Data Package... Un Data Package sert à regrouper une ou plusieurs ["ressources"](https://specs.frictionlessdata.io/data-package/#specification) entendues comme des données (fichiers CSV par exemple), par des schémas.

**Comment by thbar** [comment]
Merci @johanricher pour le commentaire et les clarifications - c'est bon à savoir clairement... On garde ouvert on va revisiter ça ! (peut-être mettre à jour le README avec ces infos à terme etc).

**Comment by thbar** [comment]
je vois que c'est utilisé pour valider le package ici:

```
❯ frictionless validate datapackage.json

# -----
# valid: statique/exemple-valide-statique.csv 
# -----

## Summary 

+------------------------+--------------------------------------+
| Description            | Size/Name/Count                      |
+========================+======================================+
| File name              | statique/exemple-valide-statique.csv |
+------------------------+--------------------------------------+
| File size (KB)         | 1648                                 |
+------------------------+--------------------------------------+
| Total Time Taken (sec) | 0.02                                 |
+------------------------+--------------------------------------+


# -----
# valid: dynamique/exemple-valide-dynamique.csv 
# -----

## Summary 

+------------------------+----------------------------------------+
| Description            | Size/Name/Count                        |
+========================+========================================+
| File name              | dynamique/exemple-valide-dynamique.csv |
+------------------------+----------------------------------------+
| File size (bytes)      | 327                                    |
+------------------------+----------------------------------------+
| Total Time Taken (sec) | 0.006                                  |
+------------------------+----------------------------------------+
```

Si je modifie le chemin ça plante.

Bon l'explication me paraît suffisante même si le nom de l'attribut est peu explicite.

Merci !
