### ISSUE TITLE
Ajouter la contrainte id_pdc_itinerance ne doit pas être la valeur d'exemple

### ISSUE THREAD

**Issue by Manu1400** [etalab/schema-irve#38]
## anomalie dans une donnée "dynamique"
Dans https://www.data.gouv.fr/fr/datasets/irve-dynamique-organisation-veterinaire-duras/

id_pdc_itinerance vaut `FRA68E680210015`, soit la valeur fournie en exemple dans la [documentation actuelle](https://schema.data.gouv.fr/etalab/schema-irve-dynamique/latest/documentation.html)

## rapport
Le [rapport actuel de validation](https://validata.fr/table-schema?input=url&url=https%3A%2F%2Fstatic.data.gouv.fr%2Fresources%2Firve-dynamique-organisation-veterinaire-duras%2F20230523-131804%2Fdata.csv&schema_url=https%3A%2F%2Fschema.data.gouv.fr%2Fschemas%2Fetalab%2Fschema-irve-dynamique%2F2.2.0%2Fschema-dynamique.json) ne remonte aucune erreur pourtant : 

> Fichier valide
[data.csv](https://static.data.gouv.fr/resources/irve-dynamique-organisation-veterinaire-duras/20230523-131804/data.csv) (8 colonnes × 1 lignes)
> Aucune erreur détectée

## solution proposée
ajouter une contrainte, soit dans le [schema](https://github.com/etalab/schema-irve/blob/master/dynamique/schema-dynamique.json#L58), soit de façon moins transparente en dur dans le logiciel de validation

**Comment by thbar** [comment]
Un point à noter est que dans:
- #48 

J'ai été amené à injecter des données réelles dans les tests, ce qui pourrait interférer avec ce ticket.

**Comment by thbar** [comment]
Au final on pourra éventuellement détecter ça dans d'autres processus que la validation, car ça me paraît compliqué à faire via la validation telle qu'elle est disponible aujourd'hui. 

Par contre je note ce point pour la réalisation suivante, où ça aura peut-être sa place:
- https://github.com/etalab/transport-site/issues/3219

Merci pour la remontée toutefois, on garde ça en tête !
