### ISSUE TITLE
Qualité des métadonnées associées à notre jeu de données

### ISSUE THREAD

**Issue by mobilygreen** [etalab/schema-irve#40]
Bonjour,
Nous avons 4 "alertes" sur la qualité de nos métadonnées :
- DESCRIPTION
- DOCUMENTATION
- COUVERTURE TEMPORELLE
- COUVERTURE SPATIALE
Nous prenons acte de ces alertes, mais comment y remédier...?
A quel endroit améliorer la DESCRIPTION ?
Où ajouter une DESCRIPTION de nos ressources ? Et qu'entendez-vous par DESCRIPTION de nos ressources ?

Merci d'avance pour vos retours.

M. Eric COLMAR

**Comment by thbar** [comment]
Hello @mobilygreen - pour ces questions, merci de contacter le PAN via https://transport.data.gouv.fr/, nous ne pourrons pas répondre sur ce ticket !
